name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 18 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
          Run withastro/action@v1
Run len=`echo $INPUT_PM | wc -c`
Run pnpm/action-setup@v2
Running self-installer...
Installation Completed!
Run actions/setup-node@v3
Found in cache @ /opt/hostedtoolcache/node/18.18.2/x64
Environment details
/home/runner/setup-pnpm/node_modules/.bin/pnpm store path --silent
/home/runner/setup-pnpm/node_modules/.bin/store/v3
pnpm cache is not found
Run cd .
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +471
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 471, reused 0, downloaded 205, added 205
Progress: resolved 471, reused 0, downloaded 471, added 471, done
.../esbuild@0.19.5/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.19.5/node_modules/esbuild postinstall: Done
.../esbuild@0.18.20/node_modules/esbuild postinstall: Done
.../sharp@0.32.6/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
.../sharp@0.32.6/node_modules/sharp install: sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-x64.tar.br
.../sharp@0.32.6/node_modules/sharp install: sharp: Integrity check passed for linux-x64
.../sharp@0.32.6/node_modules/sharp install: Done

dependencies:
+ @astrojs/check 0.2.1
+ astro 3.3.4
+ typescript 5.2.2

Done in 3.9s
Run cd .

> portfolio@0.0.1 build /home/runner/work/astro-portfolio/astro-portfolio
> astro check && astro build

06:57:54 AM [content] No content directory found. Skipping type generation.
06:57:54 AM [check] Getting diagnostics for Astro files in /home/runner/work/astro-portfolio/astro-portfolio...
src/components/SkillsList.astro:19:28 - error ts(2339): Property 'name' does not exist on type 'object'.

19                     {skill.name}
                              ~~~~
src/components/SkillsList.astro:18:58 - error ts(2339): Property 'type' does not exist on type 'object'.

18                 <li class="skill-item" skill-type={skill.type} title={skill.keywords} keywords={skill.keywords}>
                                                            ~~~~
src/components/SkillsList.astro:18:103 - error ts(2339): Property 'keywords' does not exist on type 'object'.

18                 <li class="skill-item" skill-type={skill.type} title={skill.keywords} keywords={skill.keywords}>
                                                                                                         ~~~~~~~~
src/components/SkillsList.astro:18:87 - error ts(2322): Type '{ children: any; "skill-type": any; class: string; title: any; keywords: any; }' is not assignable to type 'LiHTMLAttributes'.
  Property 'keywords' does not exist on type 'LiHTMLAttributes'.

18                 <li class="skill-item" skill-type={skill.type} title={skill.keywords} keywords={skill.keywords}>
                                                                                         ~~~~~~~~
src/components/SkillsList.astro:18:77 - error ts(2339): Property 'keywords' does not exist on type 'object'.

18                 <li class="skill-item" skill-type={skill.type} title={skill.keywords} keywords={skill.keywords}>
                                                                               ~~~~~~~~
src/components/SkillsList.astro:46:11 - error ts(2322): Type 'HTMLElement | null' is not assignable to type 'Element'.
  Type 'null' is not assignable to type 'Element'.

46     const textInput: Element = document.getElementById("filter-text-input");
             ~~~~~~~~~
src/components/SkillsList.astro:32:40 - error ts(2531): Object is possibly 'null'.

32             const keywords: string[] = item.getAttribute("keywords").split(",");
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/components/SkillsList.astro:29:15 - error ts(2741): Property 'item' is missing in type 'Element[]' but required in type 'NodeListOf<Element>'.

29         const skillItems: NodeListOf<Element> = Object.values(document.getElementsByClassName("skill-item"));
                 ~~~~~~~~~~
src/components/SkillsList.astro:26:44 - error ts(2339): Property 'value' does not exist on type 'EventTarget'.

26         const input: string = event.target.value;
                                              ~~~~~
src/components/SkillsList.astro:26:31 - error ts(18047): 'event.target' is possibly 'null'.

26         const input: string = event.target.value;
                                 ~~~~~~~~~~~~
src/components/SkillsList.astro:17:29 - warning ts(6133): 'index' is declared but its value is never read.

17         {skills.map((skill, index) => (
                               ~~~~~

src/components/Table.astro:25:30 - error ts(7053): Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.

25                         <td>{item[k]}</td>
                                ~~~~~~~
src/components/Table.astro:22:56 - error ts(2339): Property 'description' does not exist on type 'object'.

22                 <tr class="row" data-description={item.description}>
                                                          ~~~~~~~~~~~
src/components/Table.astro:55:70 - error ts(2554): Expected 1 arguments, but got 2.

55         row.addEventListener("mouseenter", e => onHoverExperience(e, index));
                                                                        ~~~~~
src/components/Table.astro:40:50 - error ts(2339): Property 'getAttribute' does not exist on type 'EventTarget'.

40         const description: string = event.target.getAttribute("data-description");
                                                    ~~~~~~~~~~~~
src/components/Table.astro:40:37 - error ts(18047): 'event.target' is possibly 'null'.

40         const description: string = event.target.getAttribute("data-description");
                                       ~~~~~~~~~~~~
src/components/Table.astro:35:15 - error ts(2322): Type 'HTMLElement | null' is not assignable to type 'HTMLElement'.
  Type 'null' is not assignable to type 'HTMLElement'.

35         const descriptionSection: HTMLElement = document.getElementById("row-description");
                 ~~~~~~~~~~~~~~~~~~
src/components/Table.astro:34:44 - error ts(2355): A function whose declared type is neither 'undefined', 'void', nor 'any' must return a value.

34     function setDescription(text: string): string {
                                              ~~~~~~
src/components/Table.astro:57:24 - warning ts(6133): 'index' is declared but its value is never read.

57     rows.forEach((row, index) => {
                          ~~~~~
src/components/Table.astro:47:34 - warning ts(6133): 'event' is declared but its value is never read.

47     function onUnhoverExperience(event: Event): void {
                                    ~~~~~

src/pages/education.astro:18:4 - error ts(2322): Type '{ headers: string[]; rowKeys: string[]; rowsInfo: object[]; setDescription: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'setDescription' does not exist on type 'IntrinsicAttributes & Props'.

18    setDescription="setDescriptionText"
      ~~~~~~~~~~~~~~

src/pages/index.astro:18:4 - error ts(2322): Type '{ headers: string[]; rowKeys: string[]; rowsInfo: object[]; setDescription: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'setDescription' does not exist on type 'IntrinsicAttributes & Props'.

18    setDescription="setDescriptionText"
      ~~~~~~~~~~~~~~

src/pages/projects.astro:18:4 - error ts(2322): Type '{ headers: string[]; rowKeys: string[]; rowsInfo: object[]; setDescription: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'setDescription' does not exist on type 'IntrinsicAttributes & Props'.

18    setDescription="setDescriptionText"
      ~~~~~~~~~~~~~~

Result (13 files):
- 20 errors
- 0 warnings
- 3 hints

 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1